# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'habit_tracker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for habit_tracker

  target 'habit_trackerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
